### ISSUE TITLE
Hide core components in GUI unless selected

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#278]
Lets hide the core components in the KX-Portal's tab unless specifically selected in the tab.

**Comment by burakkylp** [comment]
Hi @patdel76 - Like that? 

![image](https://user-images.githubusercontent.com/35352534/187310988-0c65ece1-936e-4398-ba55-98b477ff6d6e.png)

**Comment by burakkylp** [comment]
Hi @patdel76 
added a new filter option to hide core applications. Hidden per default.

![image](https://user-images.githubusercontent.com/35352534/187315254-fe3193fd-d79c-4ee1-b3e2-d96cde2c7fca.png)

**Comment by patdel76** [comment]
Perfect. Thanks @burakkylp !
