### ISSUE TITLE
Application components not consistent when description text not all of same length

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#279]
HI @burakkylp , can we update the application component, so that they all look the same? Now that I have added the descriptions to the metadata, they look different.

![image](https://user-images.githubusercontent.com/8320300/184598903-bc352db8-9a41-4069-a72f-55509b5bad00.png)

**Comment by burakkylp** [comment]
Hi @patdel76 

Removed Description in Application Cards. Instead added an info icon with tooltip on hover with Description content for each application.

![image](https://user-images.githubusercontent.com/35352534/187307710-86181e40-ef54-42cc-85e1-412d1dd68b0f.png)
