### ISSUE TITLE
Blank screen in KX-Portal from page 4 onwards

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#280]
Hi @burakkylp , there is a blank screen from page 4 onwards in the KX-Portal application page. Maybe an error due to the new combined metadata.json that needs correcting and needs handling?

![image](https://user-images.githubusercontent.com/8320300/184599229-20c4afd5-b17c-42d8-a8a9-104598624a41.png)

**Comment by burakkylp** [comment]
fixed in d86c79c5

**Comment by patdel76** [comment]
> fixed in d86c79c5

Hi @burakkylp , just add the issue number to your commit, and it will be added automatically. I just put it as “[#123] - Change description“ :)
