### ISSUE TITLE
Get version number dynamically from versions.json

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#326]
Hi @burakkylp ,
Would be be great if you could get the KX.AS.CODE version number from versions.json in the repository root for displaying in the client. Currently it says 0.8.5.
https://github.com/Accenture/kx.as.code/blob/main/versions.json
Thanks,
Patrick

**Comment by burakkylp** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/35352534/188194506-c042db45-8e05-400a-86c7-b0e9aa67ef81.png">

**Comment by burakkylp** [comment]
@patdel76 - please copy versions.json into /client/src/data because reactJs can't load files outside client source directory.
