### ISSUE TITLE
Make it visible on application cards when an app has available tasks

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#329]
Hi @burakkylp ,
I was thinking it would be useful to have some kind of indicator on the application cards that shows that there are tasks available for the application in question after installation.
Can you find a way to do that?
Thanks!
Patrick

**Comment by burakkylp** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/35352534/188622564-f179e64b-1da9-40fd-886f-41e1b181045b.png">
