### ISSUE TITLE
[Documentation] Broken links in documentation (inter-page links)

### ISSUE THREAD

**Issue by philipplewe** [Accenture/kx.as.code#645]
While reading the documentation,
I found out, that there are a lot of broken links on the documentation pages (https://accenture.github.io/kx.as.code/).
The main navigation is fine, but direct links between the pages often seem to be broken.

When I locally build the page with `mkdoc build` or `mkdoc serve` I can see a lot of warnings / errors reported by mkdocs as well:

<img width="1900" alt="Screenshot 2024-02-23 at 13 48 21" src="https://github.com/Accenture/kx.as.code/assets/11899485/bd0c41b8-2359-43f6-b016-af1545c2cba5">

Interestingly the documentation as is locally does not have broken links, when I test the site.
When I locally try to fix the warning by correcting the link to proper Markdown syntax (directly referencing the .md file via relative links), the warning disappears and it results in the same working output on the local site.

So my guess is, that the current, non-proper buildup of the links is only breaking on github pages due to the additional context path `kx.as.code` in the URLs. Fixing all the warnings from mkdocs, it should fix all broken links on github pages as well.

**Comment by philipplewe** [comment]
note: need to change all links so that they follow the guidelines here: https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages

**Comment by philipplewe** [comment]
The issue was fixed with merge of https://github.com/Accenture/kx.as.code/pull/647.

**Comment by patdel76** [comment]
Thanks @philipplewe  for taking care of this issue! <3
