### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property: git_docs_user for class: groovy.lang.Binding

### ISSUE THREAD

**Issue by ganesh35** [Accenture/kx.as.code#88]
Where: Release 0.7.1

git_docs_username is defined in jenkins.env,  but in some places it is referred as git_docs_user

Also, same with git_techradar_user
groovy.lang.MissingPropertyException: No such property: git_techradar_user for class: groovy.lang.Binding

**Comment by patdel76** [comment]
The docs and techradar installations have been removed, so closing with issue.
